#!/bin/sh
set -e

if ! docker image list captermscrn --format '{{.ID}}' | grep -q .
then
    docker container ls --all --filter 'name=captermscrn' --format '{{.ID}}' \
        | xargs docker rm
    docker run --name captermscrn golang:1.21-alpine sh -ec '
        go install github.com/tingstad/termscreen/cmd@latest'
    docker commit $(docker container ls --all --filter 'name=captermscrn' \
        --format '{{.ID}}') captermscrn
fi 2>/dev/null >&2

test -t 0 && _tty='-t' || _tty=''
docker run --rm -i $_tty captermscrn sh -ec '
    cd /go/pkg/mod/github.com/tingstad/termscreen*/
    go run cmd/main.go'

